### ISSUE TITLE
Posts are not rendered properly

### ISSUE THREAD

**Issue by vpetersson** [vpetersson/blog.viktorpetersson.com#2]
@johnnykramer It doesn't seem like the posts are rendering properly after I landed the PR.

Here's an example:
https://vpetersson.github.io/blog.viktorpetersson.com/post/92729912714/year-2010-nokia-relaunches-dangers-sidekick-2

**Comment by johnnykramer** [comment]
@vpetersson https://github.com/vpetersson/blog.viktorpetersson.com/pull/3/commits/5dcfd5d9c4c9e3f44aa4cb63d7dd76f832e21ab7

**Comment by vpetersson** [comment]
Sorry. My bad. Works now. My bad.
